fix mocha test error
1) should emit the error on app

1) Errors should emit the error on app:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is
being called in this test.